id: IB8457C62
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T20:14:27.366799'
last_modified: '2022-06-18T20:14:27.366816'
parser: null
source_metadata:
  title: Instructions on the view of the Middle Way (block print), colophon excerpt
  author: རོང་སྟོན་ཤེས་བྱ་ཀུན་རིག
  description: 'Digital version 1.0 {Tibetan}, diplomatic edition of witness A; master
    xml (completed: 2020-05-19); revision in process, thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Excerpt/Colophon'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:Mathias Fermer (mf)
  - Editorial process:-
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/1679
  bases:
    3a30:
      title: Instructions on the view of the Middle Way (block print), colophon excerpt
      order: 1
      base_file: 3a30.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
